### ISSUE TITLE
Naming Issue

### ISSUE THREAD

**Issue by LostKobrakai** [bradfrost/patternlab#15]
In /scss/base/_forms.scss it's called

``` scss
.has-error{
        border-color: $error;
}
```

while /patterns/00-Atoms/03-Forms/00-Text-Fields.php contains:

``` html
<input class="is-error" type="text" placeholder="Text Input">
```

Greetings 
Benjamin
